FROM golang:1.10-alpine3.8  as base-golang

RUN mkdir /app 
ADD *.go /app/ 
WORKDIR /app 
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM scratch
COPY --from=base-golang /app/main .
CMD ["/main"]

